name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        rust-toolchain: [stable]
        os: [ubuntu-latest, macos-11]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            name: linux
            rust_abi: unknown-linux-gnu
          - os: macos-11
            name: darwin
            rust_abi: apple-darwin
          - arch: amd64
            rust_arch: x86_64
          - arch: arm64
            rust_arch: aarch64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.rust_arch }}-${{ matrix.rust_abi }}
          default: true
          override: true

      - name: Install C cross-compilation toolchain
        if: ${{ matrix.name == 'linux' && matrix.arch != 'amd64' }}
        run: |
          sudo apt install -f -y gcc-${{ matrix.rust_arch }}-linux-gnu
          echo CC=${{ matrix.rust_arch }}-linux-gnu-gcc >> $GITHUB_ENV
          echo RUSTFLAGS='-C linker=${{ matrix.rust_arch }}-linux-gnu-gcc' >> $GITHUB_ENV

      - name: Extract tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all --locked --target=${{ matrix.rust_arch }}-${{ matrix.rust_abi }}

      - name: Strip symbols (linux)
        if: ${{ matrix.name == 'linux' }}
        run: |
          ${{ matrix.rust_arch }}-linux-gnu-strip target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release/fastly-inspect${{ matrix.extension }}

      - name: Strip symbols (non-linux)
        if: ${{ matrix.name != 'linux' }}
        run: |
          strip target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release/fastly-inspect${{ matrix.extension }}

      - name: Package
        run: |
          cp LICENSE README.md target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release/
          cd target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release
          tar czf LICENSE README.md fastly-inspect_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz fastly-inspect${{ matrix.extension }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release/fastly-inspect_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}